### ISSUE TITLE
how get id of kick.com?

### ISSUE THREAD

**Issue by TOWUK** [kbd0t/kick-followbot#1]
maybe use username?

**Comment by kbd0t** [comment]
Here's the image of how to get ID (also script doesn't work for now, I'm trying to fix it)  
I'm gonna think about adding following by username instead, but it will require me to use something else instead of user-script
  
![image](https://github.com/kbd0t/kick-followbot/assets/47297843/71b0ed40-5b2c-4852-9e46-20f60960138c)
